spring:
  datasource:
    url: jdbc:sqlserver://server5011.database.windows.net:1433;database=sqlDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sarvesh@server5011
    password: Password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      
server:
  port: 8091
  
